server:
  port: 8083

spring:
  application:
    name: BASKET-SERVICE

#    konfiguracja komunikacji z eureka
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
