server:
  port: 8081

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/user?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true&characterEncoding=UTF-8&useUnicode=yes
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    #    generate-ddl: true
    show-sql: true

#    konfiguracja komunikacji z eureka
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#      zipkin ?ledzi wszystkie wywo?ania pomi?dzy mikroserwisami.
