server:
  port: 8086

spring:
  application:
    name: NOTIFICATION-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/notification?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true&characterEncoding=UTF-8&useUnicode=yes
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    #    generate-ddl: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: notificationspring
    password: ${MAIL_PASSWORD:zaq12wsx!@}
    properties:
      mail:
        smtp:
          ssl:
            trust: smtp.gmail.com
          auth: true
          starttls:
            enable: true
            require: true
        transport:
          protocol: smtp


#    konfiguracja komunikacji z eureka
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#      zipkin ?ledzi wszystkie wywo?ania pomi?dzy mikroserwisami.
